ethereum:
  # for the demonstration purpose, we are using a hardcoded RPC URL
  rpc_url: "https://rpc.ankr.com/eth/b118e7a23420a8bbe1d20b05f724e1c790dea4736970b29cde00c0abd583b407"

database:
  path: "./sqlite.db"

server:
  port: "8080"


